function scelta = comandiFigura()
    fprintf("0 - Cerchio\n" + ...
            "1 - Poligono\n" + ...
            "Nel caso di un cerchio tenere premuto il tasto sinistro del mouse e trascinare verso l'esterno.\n" + ...
            "Nel caso di un poligono, scegliere i vertici\n");
   
    scelta = input("Scegli il tipo di figura\n");
end